return {
  formatters_by_ft = {
    bash = { "shfmt" },
    c = { "clang_format" },
    cpp = { "clang_format" },
    css = { "prettier" },
    gdscript = { "gdformat" },
    go = { "goimports", "gofmt" },
    html = { "prettier" },
    javascript = { "prettier" },
    javascriptreact = { "prettier" },
    json = { "prettier" },
    jsonc = { "prettier" },
    lua = { "stylua" },
    markdown = { "prettier" },
    python = { "ruff_organize_imports", "ruff_format" },
    rust = { "rustfmt" },
    sh = { "shfmt" },
    terraform = { "terraform_fmt" },
    ["terraform-vars"] = { "terraform_fmt" },
    toml = { "taplo" },
    typescript = { "prettier" },
    typescriptreact = { "prettier" },
    yaml = { "prettier" },
    zig = { "zigfmt" },
  },

  format_on_save = {
    timeout_ms = 1500,
    lsp_format = "fallback",
  },
}
